In [41]:
import numpy as np
import pandas as pd

In [42]:
data = pd.read_csv('C:/Users/karan/tco_amos_std.csv')
data

,"('WW1',)","('WW3',)","('WW2',)","('WW4',)","('WW9',)","('WW10',)","('WW5',)","('WW6',)","('WW7',)","('WW8',)",...,CNT,INC,INO,INS,NO_INJURY,STATE,PPN,INR,ST,LOG_INR
0,0.200252,1.105542,-0.942190,-0.588432,-0.345183,-0.878377,-0.233064,-0.425076,-0.481266,1.393408,...,El Paso,0,0,2850,74.020752,Texas,839238,339.593774,1,5.827750
1,-0.159645,0.169683,0.487120,-0.448252,-0.351857,0.875734,-0.336131,-0.431485,-0.483703,0.392183,...,Jasper,1,1,128,74.852071,Texas,35529,360.269076,1,5.886851
2,-0.153825,0.411230,0.025274,-0.501145,-0.349574,0.605984,-0.328777,-0.379666,-0.480748,0.246918,...,Dallas,1,1,9934,65.292853,Texas,2635516,376.928085,1,5.932054
3,0.383412,0.600505,0.057832,-0.113251,-0.345898,-0.563845,-0.212982,-0.189726,-0.476633,0.474526,...,Lubbock,2,1,1596,61.159202,Texas,310569,513.895463,1,6.242020
4,-0.156354,0.300858,0.431593,-0.384729,-0.351153,0.285797,-0.329199,-0.428554,-0.483703,1.720866,...,Harris,0,0,13527,72.453882,Texas,4713325,286.994850,1,5.659464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,-0.159645,0.407729,-0.192016,0.161832,-0.351857,-0.417156,-0.336131,-0.431485,0.897509,-0.176092,...,RIO BLANCO,2,1,25,72.058824,Colorado,6442,388.078237,2,5.961207
1181,-0.159645,0.499528,-1.463749,-0.601903,-0.351857,-0.894357,9.579156,-0.431485,-0.483703,-0.176092,...,BACA,0,0,10,72.727273,Colorado,3490,286.532951,2,5.657854
1182,9.491873,0.602662,-0.993761,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,1.149731,-0.176092,...,LAKE,1,1,26,26.086957,Colorado,7395,351.588911,2,5.862463
1183,-0.159645,0.948974,-1.463749,2.860363,-0.351857,-1.401383,2.780103,-0.431485,-0.483703,-0.176092,...,CHEYENNE,1,1,9,60.000000,Colorado,1719,523.560209,2,6.260652
1184,-0.159645,1.498297,-1.463749,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,-0.483703,-0.176092,...,SEDGWICK,0,0,2,50.000000,Colorado,2326,85.984523,2,4.454167

In [43]:
data.columns

Index(['('WW1',)', '('WW3',)', '('WW2',)', '('WW4',)', '('WW9',)', '('WW10',)',
       '('WW5',)', '('WW6',)', '('WW7',)', '('WW8',)', '('LL1',)', '('LL2',)',
       '('LL3',)', '('LL4',)', '('LL5',)', '('LL6',)', '('LL7',)', '('LL8',)',
       '('HF1',)', '('HF2',)', '('RR1',)', '('RR2',)', '('RR4',)', '('RR3',)',
       '('RR5',)', '('RR6',)', '('RR7',)', '('RR8',)', '('YES_INJURY',)',
       '('IN1',)', '('IN2',)', '('IN3',)', '('IN4',)', '('IN5',)', '('IN6',)',
       '('YCA',)', '('Y19',)', '('Y20',)', '('Y21',)', '('ST2',)', '('ST3',)',
       '('ST1',)', 'Crash_ID', 'COUNTY_FIPS', 'CNT', 'INC', 'INO', 'INS',
       'NO_INJURY', 'STATE', 'PPN', 'INR', 'ST', 'LOG_INR'],
      dtype='object')

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [46]:
y = data['INR']
y

0       339.593774
1       360.269076
2       376.928085
3       513.895463
4       286.994850
           ...
1180    388.078237
1181    286.532951
1182    351.588911
1183    523.560209
1184     85.984523
Name: INR, Length: 1185, dtype: float64

In [47]:
y = y.array.reshape(-1,1)
y

<PandasArray>
[
[339.5937744],
[360.269076],
[376.9280854],
[513.8954628],
[286.9948497],
[697.5373779],
[679.4436254],
[766.4689983],
[850.8588859],
[758.4463342],
[402.1757239],
[499.3314961],
[655.9898661],
[342.2092113],
[224.0280687],
[242.1080988],
[483.2142805],
[615.6275937],
[468.0682427],
[431.5589354],
[345.6375839],
[327.8452714],
[507.4911232],
[478.5792539],
[548.9634886],
[769.4918604],
[400.0144432],
[439.2104132],
[399.9514207],
[319.1534036],
[575.7052389],
[297.4856498],
[4096.280326],
[376.0345478],
[275.7773205],
[487.8593018],
[386.7657849],
[664.1640196],
[198.2383653],
[428.7434294],
[696.0158722],
[208.0848799],
[475.2305849],
[336.0089602],
[335.0578105],
[490.5676447],
[380.5084857],
[368.8700376],
[374.8247223],
[307.2697347],
[662.6612476],
[417.1491024],
[655.3418988],
[500.4843397],
[502.4221785],
[344.5845407],
[376.445281],
[749.6778728],
[2273.188553],
[510.1941464],
[4678.56524],
[364.7403597],
[443.6364102],
[629.6051281],
[178.9838895],
[700.6766809],
[416.3014899],
[454.3538339],
[448.9852932],
[341.7923027],
[418.1028023],
[1054.92722],
[443.7427998],
[479.7009656],
[524.7376312],
[597.4824526],
[598.0196235],
[264.2444261],
[521.4766022],
[367.5208848],
[517.3404867],
[1760.969977],
[326.4715657],
[444.8038819],
[592.1115462],
[965.0672829],
[248.0897092],
[702.55432],
[18.70448089],
[282.0842471],
[443.5742171],
[517.459235],
[1477.955912],
[381.18601],
[404.8671312],
[252.3240372],
[374.4880047],
[432.5962362],
[460.9950308],
[395.0844705],
[511.9825708],
[358.037952],
[1562.5],
[1544.846668],
[466.1694193],
[479.3639659],
[177.6790672],
[396.8253968],
[518.3657544],
[369.2280961],
[405.2849153],
[470.5091581],
[472.0730659],
[1027.146001],
[390.7666277],
[508.3532363],
[491.5765031],
[556.4041021],
[697.1340046],
[482.9148072],
[318.2049975],
[702.861651],
[309.6305787],
[858.0152672],
[331.8169655],
[329.5530147],
[266.4192061],
[301.2896323],
[328.9118947],
[526.0685768],
[511.3383726],
[1216.089804],
[912.4941507],
[119.0142817],
[941.6671933],
[537.595482],
[963.9459189],
[571.6798593],
[657.5781877],
[13055.1817],
[428.1345566],
[91.88361409],
[288.6534623],
[182.7652381],
[229.7631672],
[443.0819342],
[536.7768849],
[652.6898734],
[415.8695833],
[504.0322581],
[338.3596911],
[407.6878276],
[358.1421377],
[390.2215081],
[388.0938355],
[430.0421354],
[522.0763723],
[497.8596687],
[477.1458006],
[407.8922406],
[660.7580913],
[340.9976617],
[353.9823009],
[248.6782847],
[268.8841309],
[1204.227083],
[531.8542719],
[574.7922438],
[1141.856976],
[604.544507],
[317.8928247],
[218.4151252],
[900.9009009],
[854.1793777],
[357.0184605],
[305.635148],
[636.158424],
[474.0747527],
[860.0028197],
[1061.173533],
[2533.394749],
[712.4298047],
[433.8579328],
[223.7762238],
[184.7223731],
[303.2653925],
[380.3084724],
[489.3688829],
[195.8162193],
[385.7142857],
[285.6298631],
[454.550607],
[365.0586701],
[209.168555],
[227.5910364],
[413.6626876],
[1656.3147],
[1231.060606],
[683.9555429],
[1106.770833],
[136.8738024],
[399.7289973],
[337.4870197],
[450.5880556],
[319.642001],
[413.8513514],
[904.2553191],
[585.4800937],
[443.8642298],
[214.5922747],
[230.7692308],
[154.6551191],
[559.3694381],
[130.9243257],
[597.5578072],
[322.4206349],
[1348.474095],
[496.3600265],
[472.3944494],
[534.1750637],
[32.35584619],
[619.0208216],
[202.4291498],
[463.9737991],
[1417.525773],
[129.3661061],
[199.8667555],
[293.6453315],
[410.4758051],
[449.8565113],
[520.7187385],
[549.9685732],
[1903.397462],
[513.6309759],
[244.0016267],
[148.1481481],
[210.3049422],
[221.9900757],
[820.3445447],
[310.9368663],
[284.2077708],
[699.4261119],
[984.9362688],
[1987.767584],
[7673.267327],
[10650.88757],
[55.56584553],
[136.9863014],
[500.0],
[656.167979],
[409.0537224],
[5514.705882],
[173.1601732],
[452.2840344],
[187.3095094],
[329.1948834],
[533.5165612],
[533.4023822],
[843.8204699],
[224.0818549],
[282.3576867],
[624.1593317],
[329.1415268],
[331.8776467],
[369.600998],
[640.7081837],
[398.5609533],
[318.4281843],
[317.8168809],
[387.9478661],
[801.0281854],
[475.9089701],
[397.4045219],
[158.0313385],
[418.7564203],
[584.4443446],
[293.7615845],
[585.2154716],
[345.8240817],
[4227.409265],
[673.022995],
[771.606599],
[464.3054202],
[568.8450922],
[437.9623758],
[295.0591157],
[414.6875622],
[361.4022407],
[781.6418659],
[432.998007],
[355.3545469],
[523.697303],
[519.4747941],
[361.9504432],
[252.2758834],
[435.4506821],
[442.9450384],
[287.8233327],
[630.8746585],
[730.7788267],
[444.7669655],
[715.1058851],
[406.4020522],
[359.1124792],
[176.8696895],
[453.9898725],
[800.9153318],
[412.6952933],
[538.4203089],
[3903.274943],
[183.4862385],
[271.8633466],
[372.6708075],
[439.018588],
[413.3962738],
[454.9267434],
[744.6230546],
[955.0430934],
[330.7046553],
[199.0083697],
[270.0135007],
[365.6381677],
[650.3734566],
[390.815828],
[472.0143001],
[381.0588355],
[355.3454102],
[298.2240291],
[560.1120224],
[237.3700242],
[284.6317553],
[439.8261272],
[372.6322327],
[880.2217575],
[330.2042549],
[345.9362663],
[462.9183142],
[450.7562386],
[422.6888465],
[501.2644509],
[312.1748179],
[469.5524578],
[354.2276298],
[376.229282],
[330.4605146],
[406.9437061],
[448.9337823],
[472.3038415],
[530.6615449],
[351.9190586],
[640.9560022],
[555.759879],
[430.6944415],
[473.4848485],
[368.9252585],
[564.0982785],
[713.2667618],
[505.0204979],
[566.5609352],
[511.2591912],
[526.2245429],
[785.4179016],
[199.4301994],
[523.7120712],
[286.5194927],
[436.3483427],
[682.212603],
[427.7224725],
[388.6925795],
[584.9663644],
[591.0165485],
[751.9863791],
[515.8627805],
[617.9024716],
[622.8651798],
[243.2003176],
[755.0139305],
[493.6577529],
[277.0797087],
[433.0670773],
[514.4032922],
[1093.832367],
[442.1839713],
[617.2839506],
[1326.530612],
[364.6808236],
[479.835485],
[15804.5977],
[2030.352748],
[2972.465582],
[588.3848473],
[559.3025169],
[522.494608],
[249.3765586],
[489.5295078],
[388.8141169],
[442.5490827],
[573.0961254],
[325.6613122],
[252.0271751],
[394.0408075],
[352.1126761],
[1443.834825],
[282.7854366],
[713.3152174],
[310.8555188],
[10769.23077],
[25.65152971],
[274.5251835],
[1048.550533],
[524.2463958],
[797.3251029],
[723.9000113],
[689.5745676],
[1778.208859],
[1646.84355],
[373.1859019],
[607.2874494],
[376.8252473],
[409.5628155],
[406.4171123],
[19.00647948],
[548.4832069],
[1065.841499],
[227.2727273],
[252.8076231],
[735.7645553],
[393.2420623],
[834.3265793],
[597.1063309],
[363.9304488],
[396.4805562],
[341.0295405],
[618.9504181],
[679.9475128],
[367.6470588],
[441.7782738],
[368.3399006],
[537.2877713],
[279.2607803],
[268.8975202],
[426.2228537],
[477.0590711],
[462.2077216],
[1067.398597],
[331.1258278],
[609.5099701],
[221.4983713],
[844.481977],
[365.5279066],
[560.1415094],
[863.2596685],
[361.3474764],
[385.85209],
[568.1100871],
[122.5225225],
[330.4895857],
[496.9630039],
[180.091683],
[342.6257592],
[342.3444694],
[557.7109602],
[297.1768202],
[1459.854015],
[260.707635],
[344.589938],
[13567.8392],
[383.1031354],
[289.4356006],
[630.0403226],
[499.5004995],
[904.159132],
[118.3431953],
[333.4343741],
[160.9010459],
[660.3631998],
[423.8387683],
[352.1126761],
[707.4853699],
[4254.112309],
[294.2330326],
[241.084882],
[65.98482349],
[306.0443764],
[1349.892009],
[188.5014138],
[588.3401676],
[225.1914127],
[135.9832636],
[1345.29148],
[1199.563795],
[562.1135469],
[732.6007326],
[466.1168878],
[625.7110353],
[787.8787879],
[286.2254025],
[81.71755442],
[234.283483],
[397.3509934],
[61.9067272],
[95.20182788],
[453.6290323],
[451.00451],
[666.6666667],
[934.5794393],
[422.832981],
[374.5318352],
[364.6886778],
[291.8481764],
[461.1319612],
[436.3262525],
[282.6512924],
[408.0886489],
[163.5474821],
[343.5692794],
[567.4162634],
[874.2244783],
[597.1866439],
[323.9900549],
[392.8150977],
[494.1261006],
[330.1326031],
[455.3113967],
[219.6246781],
[454.0672899],
[463.4454774],
[214.2430518],
[370.4929721],
[393.4624697],
[1549.680948],
[786.7376108],
[306.1434501],
[325.936594],
[507.9674344],
[548.6211558],
[398.4691903],
[314.1213996],
[282.5384998],
[596.1028479],
[4546.079969],
[285.1332424],
[546.9532393],
[612.9876148],
[894.4815039],
[886.4133851],
[370.7436022],
[275.4935927],
[171.9157741],
[384.1117416],
[391.081724],
[729.8799646],
[1924.991703],
[489.7911011],
[377.4823568],
[951.72886],
[424.5483278],
[554.875561],
[835.1376431],
[457.8577417],
[740.6160579],
[689.5560983],
[487.1187952],
[521.8982458],
[420.7417075],
[188.8167714],
[493.7046748],
[470.1445215],
[610.0985347],
[201.9496492],
[353.6452666],
[552.5992632],
[191.5426551],
[273.0471006],
[375.4446406],
[535.8205993],
[637.5078045],
[580.218594],
[307.3868732],
[237.2419363],
[394.5744597],
[607.2874494],
[245.2209775],
[303.6734694],
[278.451074],
[363.9304488],
[554.5952175],
[160.0320064],
[286.8563367],
[312.4449921],
[1493.428913],
[216.2279042],
[598.9687857],
[5178.365938],
[295.2188387],
[412.5444805],
[480.7964251],
[545.2471694],
[422.9584364],
[679.6197465],
[329.4634694],
[707.4829932],
[583.0556878],
[235.6257758],
[533.0224036],
[2076.335878],
[2286.902287],
[540.6733841],
[560.5121744],
[695.1340616],
[399.1226493],
[741.7022066],
[303.2909499],
[189.8919077],
[436.4650828],
[505.2405267],
[419.6808217],
[279.3296089],
[588.6033869],
[395.2495479],
[342.5160249],
[13.86890418],
[464.6324946],
[419.5733495],
[524.3401061],
[892.5143954],
[274.0616871],
[283.0112396],
[438.1758345],
[59.20663114],
[380.2935331],
[469.6388411],
[525.5757129],
[576.744186],
[771.4133712],
[730.6514016],
[11.75484698],
[577.9308769],
[913.3437291],
[949.4659254],
[619.6840826],
[482.8492889],
[344.4794203],
[1506.672406],
[600.1714776],
[436.4386605],
[10619.46903],
[340.7413838],
[335.2269306],
[299.8021069],
[628.2957478],
[1395.905344],
[397.4261923],
[579.7101449],
[13851.35135],
[426.0758415],
[212.9875047],
[355.1589108],
[524.0746806],
[327.7828766],
[181.0353264],
[909.9045346],
[1845.44406],
[388.3892069],
[560.7784925],
[720.1826805],
[634.5506346],
[784.8076737],
[379.3010024],
[429.0913041],
[550.0038733],
[374.2690058],
[469.2082111],
[481.9765087],
[485.2290567],
[636.2942224],
[225.5752168],
[188.0115019],
[428.6813469],
[298.3525749],
[399.7324748],
[359.5326076],
[407.2766766],
[195.3125],
[457.8422484],
[581.9101834],
[362.5236323],
[769.9379453],
[412.7845265],
[433.2212278],
[813.0081301],
[407.2766766],
[270.7581227],
[408.4633608],
[610.9979633],
[391.9991959],
[562.2086114],
[593.7966495],
[397.1924479],
[577.5288764],
[470.8438971],
[479.473629],
[374.5318352],
[440.8407463],
[965.9613615],
[325.3325622],
[345.0212629],
[482.2182037],
[170.0680272],
[1584.507042],
[449.7880806],
[670.8407871],
[241.7962003],
[230.4934267],
[462.638441],
[529.1783037],
[765.6967841],
[432.6263586],
[643.9353953],
[1576.086957],
[660.6110652],
[431.4063848],
[501.972033],
[3803.849679],
[390.2439024],
[701.8663264],
[191.791331],
[214.2857143],
[153.5626536],
[769.7690693],
[564.0864933],
[496.1469439],
[163.5858008],
[428.8900326],
[158.5585586],
[728.2542269],
[344.7671361],
[351.8648839],
[550.4918329],
[146.1377871],
[513.7289637],
[371.0378459],
[374.5318352],
[187.1257485],
[922.3445403],
[451.1894996],
[160.1537476],
[196.6568338],
[267.3796791],
[653.5947712],
[266.1343979],
[185.1117282],
[851.970181],
[18518.51852],
[576.7012687],
[260.756193],
[662.8787879],
[282.2580645],
[1294.498382],
[1803.051318],
[147.601476],
[1171.875],
[405.8003045],
[327.2275462],
[229.8738139],
[174.6389222],
[280.0707547],
[315.6594538],
[351.0893069],
[330.5602721],
[255.1460194],
[228.6379414],
[236.4451692],
[254.246412],
[365.0540004],
[257.2634993],
[381.4879822],
[388.2802107],
[364.1368237],
[183.122884],
[195.9042942],
[278.1553022],
[313.8314931],
[355.8980543],
[330.9730608],
[310.594998],
[501.216545],
[321.5434084],
[400.5629533],
[180.1531302],
[377.1337832],
[376.6076885],
[359.8162367],
[343.4303503],
[381.6793893],
[241.1686343],
[351.4780101],
[194.0730103],
[329.2009584],
[280.214425],
[149.1496067],
[234.741784],
[231.3791759],
[194.9087473],
[365.0650163],
[347.5771826],
[276.2029365],
[219.2052044],
[240.4587213],
[458.877515],
[285.10335],
[106.2256566],
[298.1410032],
[191.7785375],
[175.7231684],
[262.5793845],
[357.3910454],
[234.6971139],
[377.324589],
[135.5748373],
[440.5286344],
[421.1511465],
[151.7241379],
[331.6102604],
[223.2765839],
[173.1730246],
[593.9123979],
[301.4811902],
[375.5954562],
[165.6751261],
[415.4165705],
[189.4451962],
[263.6038411],
[192.5770308],
[200.1819836],
[126.3206247],
[193.3356079],
[199.9333555],
[263.8522427],
[182.4561404],
[159.5532509],
[292.4957541],
[311.1629716],
[253.5273369],
[258.0359776],
[345.9062296],
[241.4553932],
[273.8521324],
[318.8717407],
[301.4524527],
[162.8599003],
[201.8660797],
[344.5471961],
[221.616527],
[228.1029175],
[345.6812487],
[280.613768],
[152.2342617],
[210.1863838],
[240.5305684],
[248.1271174],
[275.9507853],
[281.2049633],
[216.5789027],
[374.1616661],
[325.203252],
[109.1041338],
[331.0781632],
[421.1018833],
[255.1345835],
[334.4605894],
[489.0038147],
[241.5707237],
[169.1532833],
[251.1629939],
[381.9544537],
[297.7963073],
[215.299921],
[332.3668765],
[136.5008531],
[321.8459101],
[295.704727],
[172.0222941],
[302.7103133],
[126.8260604],
[344.7879554],
[282.83088],
[158.1235999],
[230.741924],
[277.9836916],
[439.0672261],
[150.3194288],
[385.2150784],
[263.1578947],
[260.756193],
[253.298153],
[118.0257511],
[285.4892695],
[369.2372613],
[420.2416389],
[122.4769743],
[388.1896248],
[161.5508885],
[329.4591379],
[104.9003447],
[294.1963092],
[127.9367295],
[340.9736693],
[377.7335984],
[218.4996358],
[173.1601732],
[424.5810056],
[276.7527675],
[204.141149],
[284.0175574],
[174.7487986],
[215.6921942],
[187.0381916],
[274.1470979],
[390.1781913],
[256.4406981],
[300.5582332],
[371.3041485],
[234.0068427],
[179.8502338],
[326.7835165],
[248.2022733],
[194.4990177],
[230.0327434],
[303.0561202],
[262.8516668],
[294.7734402],
[240.1921537],
[252.6702653],
[175.7934333],
[177.0152505],
[271.6071589],
[213.8656211],
[81.53868291],
[414.7465438],
[308.6229245],
[166.2424022],
[276.9676242],
[441.7866732],
[137.4070482],
[418.505061],
[293.8295788],
[286.5922118],
[345.8207307],
[330.9626083],
[205.7613169],
[437.4453193],
[501.7957666],
[294.5874002],
[223.3462524],
[322.9360013],
[278.3254088],
[790.1506799],
[225.1295557],
[329.1842403],
[185.9417557],
[177.2421127],
[417.0230967],
[184.6590909],
[311.9628191],
[380.4565479],
[598.0484734],
[172.1911322],
[431.664694],
[232.2019663],
[325.9604191],
[164.2335766],
[301.2048193],
[338.4810662],
[183.8946961],
[371.2025007],
[334.3549735],
[186.5532423],
[238.8189318],
[313.6308806],
[198.334859],
[311.5264798],
[245.7002457],
[411.2969564],
[297.4773917],
[229.3788421],
[414.7812971],
[210.7111501],
[148.4230056],
[59.43536404],
[160.7286365],
[208.0732418],
[339.5201449],
[832.3976027],
[551.2274375],
[857.1102472],
[585.9197852],
[692.9454764],
[679.5236863],
[782.3756073],
[564.13995],
[599.6257113],
[557.766271],
[656.0472845],
[393.9161834],
[513.5853706],
[2474.226804],
[528.4282525],
[1241.494953],
[486.6629705],
[388.0919631],
[2472.527473],
[502.270538],
[2218.355807],
[370.5437242],
[845.4276455],
[743.6125588],
[495.3002758],
[403.4754931],
[391.502471],
[880.8702574],
[977.0943457],
[377.9165297],
[471.3541203],
[415.2792847],
[706.7851373],
[1492.153332],
[353.1502877],
[488.1512381],
[243.902439],
[556.3045484],
[269.4879729],
[563.119253],
[211.0199297],
[703.1573142],
[442.9678848],
[5071.521456],
[338.6358411],
[538.3117627],
[370.2536631],
[583.9416058],
[490.1960784],
[453.82794],
[491.1419049],
[557.1030641],
[255.9414991],
[1436.781609],
[791.3247362],
[330.1137058],
[670.2038537],
[321.2994779],
[412.4081047],
[355.6187767],
[296.9806963],
[631.6218419],
[655.379574],
[667.2597865],
[417.1632896],
[570.1449169],
[595.173396],
[651.104707],
[407.5931189],
[542.884607],
[303.3964291],
[495.4347529],
[443.5061338],
[417.6008799],
[320.0684591],
[519.4265531],
[448.1013636],
[445.7470843],
[444.7852761],
[437.1090512],
[1990.844246],
[463.5803645],
[427.2259443],
[406.0585371],
[505.7335701],
[382.5708763],
[693.5260153],
[217.1983745],
[430.7246554],
[507.3746313],
[180.5235182],
[482.4471361],
[397.3181028],
[757.8367206],
[306.8865338],
[2248.005801],
[471.1789792],
[1127.874615],
[343.07474],
[380.2938634],
[311.1865503],
[1034.482759],
[220.8968412],
[1374.570447],
[409.6681688],
[379.9587841],
[773.1958763],
[278.1706742],
[438.516353],
[1142.204455],
[389.0753738],
[489.9930987],
[322.1044155],
[316.1165881],
[467.8970626],
[1406.469761],
[813.8988887],
[677.5354647],
[679.6941376],
[812.433769],
[125.5755546],
[458.9632829],
[266.2894233],
[756.0137457],
[643.5006435],
[492.2644163],
[2860.411899],
[634.5177665],
[440.2517457],
[313.6497979],
[354.5017916],
[500.0322601],
[267.1397512],
[336.3614137],
[406.3408065],
[311.2778354],
[219.0473873],
[243.6682932],
[1839.587932],
[162.0089105],
[492.0825185],
[101.7615715],
[400.1823616],
[233.5100731],
[182.7181053],
[150.1251043],
[517.4644243],
[434.5249852],
[219.9876685],
[835.3600508],
[298.0887252],
[266.5482008],
[393.1999537],
[222.7722772],
[326.8552659],
[433.0879168],
[201.511335],
[275.66232],
[129.1302697],
[340.0442597],
[507.0259308],
[91.14496797],
[644.8328525],
[191.1314985],
[340.3126262],
[372.0913671],
[320.7055522],
[285.6326764],
[1079.622132],
[358.5465076],
[286.8720192],
[123.8905701],
[501.5779982],
[334.8681457],
[432.6507067],
[263.7826431],
[636.5900913],
[349.2193919],
[629.7035786],
[529.8739265],
[336.8421053],
[243.4912905],
[343.8789546],
[261.5518745],
[3336.921421],
[276.5158997],
[96.8028537],
[388.0782366],
[286.5329513],
[351.5889114],
[523.5602094],
[85.98452279]
]
Shape: (1185, 1), dtype: float64

In [48]:
y1 = scaler.fit_transform(y)

In [49]:
y1

array([[-0.21791473],
       [-0.20076287],
       [-0.18694286],
       ...,
       [-0.20796378],
       [-0.06529949],
       [-0.42830439]])

In [50]:
y2 = pd.DataFrame(data= y1, columns=['INR_S'])

In [51]:
y2

         INR_S
0    -0.217915
1    -0.200763
2    -0.186943
3    -0.073317
4    -0.261550
...        ...
1180 -0.177693
1181 -0.261933
1182 -0.207964
1183 -0.065299
1184 -0.428304

[1185 rows x 1 columns]

In [52]:
data1 = pd.concat([data,y2],axis= 1)

In [53]:
data1

,"('WW1',)","('WW3',)","('WW2',)","('WW4',)","('WW9',)","('WW10',)","('WW5',)","('WW6',)","('WW7',)","('WW8',)",...,INC,INO,INS,NO_INJURY,STATE,PPN,INR,ST,LOG_INR,INR_S
0,0.200252,1.105542,-0.942190,-0.588432,-0.345183,-0.878377,-0.233064,-0.425076,-0.481266,1.393408,...,0,0,2850,74.020752,Texas,839238,339.593774,1,5.827750,-0.217915
1,-0.159645,0.169683,0.487120,-0.448252,-0.351857,0.875734,-0.336131,-0.431485,-0.483703,0.392183,...,1,1,128,74.852071,Texas,35529,360.269076,1,5.886851,-0.200763
2,-0.153825,0.411230,0.025274,-0.501145,-0.349574,0.605984,-0.328777,-0.379666,-0.480748,0.246918,...,1,1,9934,65.292853,Texas,2635516,376.928085,1,5.932054,-0.186943
3,0.383412,0.600505,0.057832,-0.113251,-0.345898,-0.563845,-0.212982,-0.189726,-0.476633,0.474526,...,2,1,1596,61.159202,Texas,310569,513.895463,1,6.242020,-0.073317
4,-0.156354,0.300858,0.431593,-0.384729,-0.351153,0.285797,-0.329199,-0.428554,-0.483703,1.720866,...,0,0,13527,72.453882,Texas,4713325,286.994850,1,5.659464,-0.261550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,-0.159645,0.407729,-0.192016,0.161832,-0.351857,-0.417156,-0.336131,-0.431485,0.897509,-0.176092,...,2,1,25,72.058824,Colorado,6442,388.078237,2,5.961207,-0.177693
1181,-0.159645,0.499528,-1.463749,-0.601903,-0.351857,-0.894357,9.579156,-0.431485,-0.483703,-0.176092,...,0,0,10,72.727273,Colorado,3490,286.532951,2,5.657854,-0.261933
1182,9.491873,0.602662,-0.993761,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,1.149731,-0.176092,...,1,1,26,26.086957,Colorado,7395,351.588911,2,5.862463,-0.207964
1183,-0.159645,0.948974,-1.463749,2.860363,-0.351857,-1.401383,2.780103,-0.431485,-0.483703,-0.176092,...,1,1,9,60.000000,Colorado,1719,523.560209,2,6.260652,-0.065299
1184,-0.159645,1.498297,-1.463749,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,-0.483703,-0.176092,...,0,0,2,50.000000,Colorado,2326,85.984523,2,4.454167,-0.428304

In [54]:
data1

,"('WW1',)","('WW3',)","('WW2',)","('WW4',)","('WW9',)","('WW10',)","('WW5',)","('WW6',)","('WW7',)","('WW8',)",...,INC,INO,INS,NO_INJURY,STATE,PPN,INR,ST,LOG_INR,INR_S
0,0.200252,1.105542,-0.942190,-0.588432,-0.345183,-0.878377,-0.233064,-0.425076,-0.481266,1.393408,...,0,0,2850,74.020752,Texas,839238,339.593774,1,5.827750,-0.217915
1,-0.159645,0.169683,0.487120,-0.448252,-0.351857,0.875734,-0.336131,-0.431485,-0.483703,0.392183,...,1,1,128,74.852071,Texas,35529,360.269076,1,5.886851,-0.200763
2,-0.153825,0.411230,0.025274,-0.501145,-0.349574,0.605984,-0.328777,-0.379666,-0.480748,0.246918,...,1,1,9934,65.292853,Texas,2635516,376.928085,1,5.932054,-0.186943
3,0.383412,0.600505,0.057832,-0.113251,-0.345898,-0.563845,-0.212982,-0.189726,-0.476633,0.474526,...,2,1,1596,61.159202,Texas,310569,513.895463,1,6.242020,-0.073317
4,-0.156354,0.300858,0.431593,-0.384729,-0.351153,0.285797,-0.329199,-0.428554,-0.483703,1.720866,...,0,0,13527,72.453882,Texas,4713325,286.994850,1,5.659464,-0.261550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,-0.159645,0.407729,-0.192016,0.161832,-0.351857,-0.417156,-0.336131,-0.431485,0.897509,-0.176092,...,2,1,25,72.058824,Colorado,6442,388.078237,2,5.961207,-0.177693
1181,-0.159645,0.499528,-1.463749,-0.601903,-0.351857,-0.894357,9.579156,-0.431485,-0.483703,-0.176092,...,0,0,10,72.727273,Colorado,3490,286.532951,2,5.657854,-0.261933
1182,9.491873,0.602662,-0.993761,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,1.149731,-0.176092,...,1,1,26,26.086957,Colorado,7395,351.588911,2,5.862463,-0.207964
1183,-0.159645,0.948974,-1.463749,2.860363,-0.351857,-1.401383,2.780103,-0.431485,-0.483703,-0.176092,...,1,1,9,60.000000,Colorado,1719,523.560209,2,6.260652,-0.065299
1184,-0.159645,1.498297,-1.463749,-0.601903,-0.351857,-1.401383,-0.336131,-0.431485,-0.483703,-0.176092,...,0,0,2,50.000000,Colorado,2326,85.984523,2,4.454167,-0.428304

In [55]:
data1.columns

Index(['('WW1',)', '('WW3',)', '('WW2',)', '('WW4',)', '('WW9',)', '('WW10',)',
       '('WW5',)', '('WW6',)', '('WW7',)', '('WW8',)', '('LL1',)', '('LL2',)',
       '('LL3',)', '('LL4',)', '('LL5',)', '('LL6',)', '('LL7',)', '('LL8',)',
       '('HF1',)', '('HF2',)', '('RR1',)', '('RR2',)', '('RR4',)', '('RR3',)',
       '('RR5',)', '('RR6',)', '('RR7',)', '('RR8',)', '('YES_INJURY',)',
       '('IN1',)', '('IN2',)', '('IN3',)', '('IN4',)', '('IN5',)', '('IN6',)',
       '('YCA',)', '('Y19',)', '('Y20',)', '('Y21',)', '('ST2',)', '('ST3',)',
       '('ST1',)', 'Crash_ID', 'COUNTY_FIPS', 'CNT', 'INC', 'INO', 'INS',
       'NO_INJURY', 'STATE', 'PPN', 'INR', 'ST', 'LOG_INR', 'INR_S'],
      dtype='object')

In [56]:
data1.columns = data1.columns.str.replace(r"\(\'|\'\)", "")

C:\Users\karan\AppData\Local\Temp\ipykernel_36484\3468899031.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\(\'|\'\)", "")

In [58]:
data1.columns = data1.columns.str.replace(r"\(\'|\'\)", "").str.replace(r",\s*", "")

C:\Users\karan\AppData\Local\Temp\ipykernel_36484\1151836982.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\(\'|\'\)", "").str.replace(r",\s*", "")
C:\Users\karan\AppData\Local\Temp\ipykernel_36484\1151836982.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\(\'|\'\)", "").str.replace(r",\s*", "")

In [60]:
data1.columns = data1.columns.str.replace(r"\)\s*", "").str.replace(r"\(\'|\'\)", "")

C:\Users\karan\AppData\Local\Temp\ipykernel_36484\164495156.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\)\s*", "").str.replace(r"\(\'|\'\)", "")
C:\Users\karan\AppData\Local\Temp\ipykernel_36484\164495156.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\)\s*", "").str.replace(r"\(\'|\'\)", "")

In [62]:
data1.columns = data1.columns.str.replace(r"\'", "")

C:\Users\karan\AppData\Local\Temp\ipykernel_36484\3366930830.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data1.columns = data1.columns.str.replace(r"\'", "")

In [64]:
data1.to_csv('tco_amos_std.csv',index= False)