In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/karan/tco_working_interaction.csv')

In [3]:
data

,Crash_ID,COUNTY_FIPS,COUNTY,INJURY_COUNT,INJURY_OUTCOME,INJURY_COUNT_SUM,BLOWING SAND/SNOW,CLEAR,CLOUDY,FOG,...,STATE_Colorado,STATE_Oklahoma,STATE_Texas,LOG_INJURY_RATE,MarIN,AlcIN,AlDrIN,MedIN,DrIN,NoIN
0,15585669,48141,El Paso,0,0,2850,0.324254,90.466926,4.824903,0.025940,...,0,0,1,5.827750,0.100430,0.435199,0.000000,0.033477,0.066954,257.470296
1,16473665,48241,Jasper,1,1,128,0.000000,67.751479,18.047337,0.295858,...,0,0,1,5.886851,2.450895,0.000000,0.000000,2.450895,2.450895,821.049683
2,16585839,48113,Dallas,1,1,9934,0.005244,73.614388,13.774841,0.194012,...,0,0,1,5.932054,0.411764,4.781043,0.045752,0.297385,0.503268,430.225273
3,16824710,48303,Lubbock,2,1,1596,0.489274,78.208506,14.076026,0.940911,...,0,0,1,6.242020,0.611928,0.203976,0.000000,0.815905,0.407952,539.924860
4,16824789,48201,Harris,0,0,13527,0.002966,70.935405,17.533662,0.418174,...,0,0,1,5.659464,0.035465,0.332482,0.026599,0.048764,0.062063,148.969685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,10212672,8103,RIO BLANCO,2,1,25,0.000000,73.529412,11.764706,1.470588,...,1,0,0,5.961207,45.415225,317.906574,0.000000,0.000000,0.000000,2724.913495
1181,10214252,8009,BACA,0,0,10,0.000000,75.757576,0.000000,0.000000,...,1,0,0,5.657854,82.644628,82.644628,0.000000,0.000000,0.000000,2561.983471
1182,10214428,8065,LAKE,1,1,26,8.695652,78.260870,4.347826,0.000000,...,1,0,0,5.862463,623.818526,1247.637051,0.000000,0.000000,0.000000,2911.153119
1183,10215666,8017,CHEYENNE,1,1,9,0.000000,86.666667,0.000000,6.666667,...,1,0,0,6.260652,88.888889,88.888889,0.000000,0.000000,0.000000,1155.555555
1184,10221660,8115,SEDGWICK,0,0,2,0.000000,100.000000,0.000000,0.000000,...,1,0,0,4.454167,0.000000,0.000000,0.000000,0.000000,0.000000,10000.000000

In [4]:
data.columns

Index(['Crash_ID', 'COUNTY_FIPS', 'COUNTY', 'INJURY_COUNT', 'INJURY_OUTCOME',
       'INJURY_COUNT_SUM', 'BLOWING SAND/SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS', 'SLEET/HAIL',
       'SNOW_WEATHER', 'UNKNOWN_WEATHER', 'DARK-LIGHTED', 'DARK-NOT LIGHTED',
       'DARK-UNKNOWN LIGHTING', 'DAWN', 'DAYLIGHT', 'DUSK', 'OTHER_LIGHT',
       'UNKNOWN_LIGHT', 'INATTENTION', 'SPEEDING', 'CITY STREET',
       'COUNTY ROAD', 'FARM TO MARKET', 'INTERSTATE', 'OTHER ROADS',
       'TOLL BRIDGES', 'TOLLWAY', 'US & STATE HIGHWAY', 'NO_INJURY',
       'YES_INJURY', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MARIJUANA',
       'MEDICINAL', 'NO INTOXICATION', 'YEAR_CAT', 'YEAR_2019', 'YEAR_2020',
       'YEAR_2021', 'STATE', 'POPULATION', 'INJURY_RATE', 'STATE_CAT',
       'STATE_Colorado', 'STATE_Oklahoma', 'STATE_Texas', 'LOG_INJURY_RATE',
       'MarIN', 'AlcIN', 'AlDrIN', 'MedIN', 'DrIN', 'NoIN'],
      dtype='object')

In [5]:
data['LOG_INJURY_RATE'] = np.log(data['INJURY_RATE'])

In [6]:
data.columns

Index(['Crash_ID', 'COUNTY_FIPS', 'COUNTY', 'INJURY_COUNT', 'INJURY_OUTCOME',
       'INJURY_COUNT_SUM', 'BLOWING SAND/SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS', 'SLEET/HAIL',
       'SNOW_WEATHER', 'UNKNOWN_WEATHER', 'DARK-LIGHTED', 'DARK-NOT LIGHTED',
       'DARK-UNKNOWN LIGHTING', 'DAWN', 'DAYLIGHT', 'DUSK', 'OTHER_LIGHT',
       'UNKNOWN_LIGHT', 'INATTENTION', 'SPEEDING', 'CITY STREET',
       'COUNTY ROAD', 'FARM TO MARKET', 'INTERSTATE', 'OTHER ROADS',
       'TOLL BRIDGES', 'TOLLWAY', 'US & STATE HIGHWAY', 'NO_INJURY',
       'YES_INJURY', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MARIJUANA',
       'MEDICINAL', 'NO INTOXICATION', 'YEAR_CAT', 'YEAR_2019', 'YEAR_2020',
       'YEAR_2021', 'STATE', 'POPULATION', 'INJURY_RATE', 'STATE_CAT',
       'STATE_Colorado', 'STATE_Oklahoma', 'STATE_Texas', 'LOG_INJURY_RATE',
       'MarIN', 'AlcIN', 'AlDrIN', 'MedIN', 'DrIN', 'NoIN'],
      dtype='object')

In [7]:
data.rename(columns={'DARK-LIGHTED':'LL1',
                   'DARK-NOT LIGHTED':'LL2',
                  'DARK-UNKNOWN LIGHTING':'LL3',
                   'DAWN':'LL4',
                   'DAYLIGHT':'LL5',
                  'DUSK':'LL6',
                   'OTHER_LIGHT':'LL7',
                   'UNKNOWN_LIGHT':'LL8',
                    'INATTENTION':'HF1',
                    'SPEEDING':'HF2',
                    'ALCOHOL':'IN1'
                    , 'ALCOHOL, DRUG':'IN2'
                    , 'DRUG':'IN3',
                    'MARIJUANA':'IN4'
                    ,'MEDICINAL':'IN5',
                    'NO INTOXICATION':'IN6',
                    'CITY STREET':'RR1',
       'COUNTY ROAD':'RR2',
                    'FARM TO MARKET':'RR4', 'INTERSTATE':'RR3', 'OTHER ROADS':'RR5',
       'TOLL BRIDGES':'RR6', 'TOLLWAY':'RR7', 'US & STATE HIGHWAY':'RR8',
                    'BLOWING SAND/SNOW':'WW1', 'CLEAR':'WW3', 'CLOUDY':'WW2', 'FOG':'WW4',
       'OTHER_WEATHER':'WW9', 'RAIN':'WW10', 'SEVERE CROSSWINDS':'WW5', 'SLEET/HAIL':'WW6',
       'SNOW_WEATHER':'WW7', 'UNKNOWN_WEATHER':'WW8'},inplace= True)

In [8]:
data.rename(columns={'COUNTY':'CNT',
                   'INJURY_COUNT':'INC',
                   'INJURY_OUTCOME':'INO',
                   'INJURY_COUNT_SUM':'INS',
                   'INJURY_RATE':'INR',
                    'YEAR_CAT':'YCA',
                    'YEAR_2019':'Y19', 'YEAR_2020':'Y20', 'YEAR_2021':'Y21',
                    'POPULATION':'PPN','STATE_CAT':'ST', 'STATE_Colorado':'ST2',
       'STATE_Oklahoma':'ST3', 'STATE_Texas':'ST1'},inplace= True)

In [9]:
data.columns

Index(['Crash_ID', 'COUNTY_FIPS', 'CNT', 'INC', 'INO', 'INS', 'WW1', 'WW3',
       'WW2', 'WW4', 'WW9', 'WW10', 'WW5', 'WW6', 'WW7', 'WW8', 'LL1', 'LL2',
       'LL3', 'LL4', 'LL5', 'LL6', 'LL7', 'LL8', 'HF1', 'HF2', 'RR1', 'RR2',
       'RR4', 'RR3', 'RR5', 'RR6', 'RR7', 'RR8', 'NO_INJURY', 'YES_INJURY',
       'IN1', 'IN2', 'IN3', 'IN4', 'IN5', 'IN6', 'YCA', 'Y19', 'Y20', 'Y21',
       'STATE', 'PPN', 'INR', 'ST', 'ST2', 'ST3', 'ST1', 'LOG_INJURY_RATE',
       'MarIN', 'AlcIN', 'AlDrIN', 'MedIN', 'DrIN', 'NoIN'],
      dtype='object')

In [10]:
data.rename(columns={'MarIN':'MIN','AlcIN':'AIN','AlDrIN':'ADN','MedIN':'MDIN','DrIN':'DIN','NoIN':'NIN'},inplace= True)

In [11]:
data.columns

Index(['Crash_ID', 'COUNTY_FIPS', 'CNT', 'INC', 'INO', 'INS', 'WW1', 'WW3',
       'WW2', 'WW4', 'WW9', 'WW10', 'WW5', 'WW6', 'WW7', 'WW8', 'LL1', 'LL2',
       'LL3', 'LL4', 'LL5', 'LL6', 'LL7', 'LL8', 'HF1', 'HF2', 'RR1', 'RR2',
       'RR4', 'RR3', 'RR5', 'RR6', 'RR7', 'RR8', 'NO_INJURY', 'YES_INJURY',
       'IN1', 'IN2', 'IN3', 'IN4', 'IN5', 'IN6', 'YCA', 'Y19', 'Y20', 'Y21',
       'STATE', 'PPN', 'INR', 'ST', 'ST2', 'ST3', 'ST1', 'LOG_INJURY_RATE',
       'MIN', 'AIN', 'ADN', 'MDIN', 'DIN', 'NIN'],
      dtype='object')

In [14]:
data.columns

Index(['Crash_ID', 'COUNTY_FIPS', 'CNT', 'INC', 'INO', 'INS', 'WW1', 'WW3',
       'WW2', 'WW4', 'WW9', 'WW10', 'WW5', 'WW6', 'WW7', 'WW8', 'LL1', 'LL2',
       'LL3', 'LL4', 'LL5', 'LL6', 'LL7', 'LL8', 'HF1', 'HF2', 'RR1', 'RR2',
       'RR4', 'RR3', 'RR5', 'RR6', 'RR7', 'RR8', 'NO_INJURY', 'YES_INJURY',
       'IN1', 'IN2', 'IN3', 'IN4', 'IN5', 'IN6', 'YCA', 'Y19', 'Y20', 'Y21',
       'STATE', 'PPN', 'INR', 'ST', 'ST2', 'ST3', 'ST1', 'LOG_INJURY_RATE',
       'MIN', 'AIN', 'ADN', 'MDIN', 'DIN', 'NIN'],
      dtype='object')

In [13]:
data.to_csv('tco_wrkng_intr_1.csv',index= False)

In [16]:
data.isnull().sum()

Crash_ID           0
COUNTY_FIPS        0
CNT                0
INC                0
INO                0
INS                0
WW1                0
WW3                0
WW2                0
WW4                0
WW9                0
WW10               0
WW5                0
WW6                0
WW7                0
WW8                0
LL1                0
LL2                0
LL3                0
LL4                0
LL5                0
LL6                0
LL7                0
LL8                0
HF1                0
HF2                0
RR1                0
RR2                0
RR4                0
RR3                0
RR5                0
RR6                0
RR7                0
RR8                0
NO_INJURY          0
YES_INJURY         0
IN1                0
IN2                0
IN3                0
IN4                0
IN5                0
IN6                0
YCA                0
Y19                0
Y20                0
Y21                0
STATE              0
PPN                0
INR                0
ST                 0
ST2                0
ST3                0
ST1                0
LOG_INJURY_RATE    0
MIN                0
AIN                0
ADN                0
MDIN               0
DIN                0
NIN                0
dtype: int64